Repository sesac-team-triad/for-pets-android, pull requests merged in 2024-02, with the labels that each got.

#37 아키텍쳐를 적용하였습니다.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamtriad/forpets/ForPetsApplication.kt
  app/src/main/java/com/teamtriad/forpets/data/AppointmentRepository.kt
  app/src/main/java/com/teamtriad/forpets/data/LocationRepository.kt
  app/src/main/java/com/teamtriad/forpets/data/TransportRepository.kt
  app/src/main/java/com/teamtriad/forpets/data/UserRepository.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/AdoptService.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/LoginService.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/RemoteDatabaseService.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/AbandonmentInfo.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/AbandonmentPublic.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/Appointment.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/CompletedDate.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/District.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/KeyResponse.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/Moving.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/ResponseBody.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/ResponseHeader.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/TransportReq.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/TransportVol.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/User.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/adapter/AdoptRecyclerViewAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/chat/enums/AppointmentProgress.kt
  app/src/main/java/com/teamtriad/forpets/ui/login/LoginFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/login/SignUpUserFragment.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
Labels: feat

#40 버튼의 중복 클릭 방지 기능을 구현했습니다.
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportVolFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerVolListFragment.kt
  app/src/main/java/com/teamtriad/forpets/util/Extensions.kt
  app/src/main/java/com/teamtriad/forpets/util/SafeClickListener.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: fix, improving

#41 지역 선택 다이얼로그 입력하기 버튼의 기능을 구현하였습니다.
  app/src/main/java/com/teamtriad/forpets/ui/profile/ProfileFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportListsFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportVolFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerReqListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerVolListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/adapter/ReqListRecyclerViewAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/adapter/TransportListsViewPagerAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/LocationPickerDialogFragment.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
  app/src/main/res/color/selector_button_background_color.xml
  app/src/main/res/drawable/shape_req_card_gray.xml
  app/src/main/res/drawable/shape_req_card_purple.xml
  app/src/main/res/layout/bottom_sheet_location.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_transport_lists.xml
  app/src/main/res/layout/fragment_transport_vol.xml
  app/src/main/res/layout/fragment_view_pager_req_list.xml
  app/src/main/res/layout/rv_item_req_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat

#42 봉사요청 목록 화면의 추가 기능들을 구현하였습니다.
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/TransportReq.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/AdoptDetailFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/adapter/AdoptRecyclerViewAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerReqListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/LocationPickerDialogFragment.kt
  app/src/main/java/com/teamtriad/forpets/util/Extensions.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
  app/src/main/res/layout/fragment_view_pager_req_list.xml
  app/src/main/res/values/strings.xml
Labels: feat, improving

#44 봉사자 글 등록 화면 구현
  app/src/main/java/com/teamtriad/forpets/ui/profile/ProfileFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportListsFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportVolFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/adapter/DistrictPickerRecyclerViewAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/DistrictPickerDialogFragment.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/layout/bottom_sheet_vol_district.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_transport.xml
  app/src/main/res/layout/fragment_transport_vol.xml
  app/src/main/res/layout/fragment_view_pager_vol_list.xml
  app/src/main/res/layout/rv_item_vol_district.xml
  app/src/main/res/layout/rv_item_vol_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, fix, improving

#46 봉사요청 글 등록 화면에 아키텍쳐를 적용했습니다.
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/LocationPickerDialogFragment.kt
  app/src/main/res/layout/fragment_transport_req.xml
Labels: feat, improving, 리뷰요청

#49 이동중 목록 화면을 구현하였습니다.
  app/src/main/java/com/teamtriad/forpets/data/source/network/model/Appointment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportMovingListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/adapter/MovingListRecyclerViewAdapter.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
  app/src/main/res/layout/fragment_transport_moving_list.xml
  app/src/main/res/layout/rv_item_moving_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feat

#51 이동봉사 화면에 아키텍쳐를 적용했습니다.
  app/src/main/java/com/teamtriad/forpets/ui/MainActivity.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerReqListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/marker/Item.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/marker/MarkerItem.kt
  app/src/main/java/com/teamtriad/forpets/viewmodel/TransportViewModel.kt
  app/src/main/res/layout/fragment_transport.xml
Labels: feat, improving, 리뷰요청
