Repository sesac-team-triad/for-pets-android, pull requests merged in 2024-01, with the labels that each got.

#29 Open API 로직 변경 및 예외 처리하기
  app/src/main/java/com/teamtriad/forpets/data/source/network/AbandonmentPublic.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/AdoptService.kt
  app/src/main/java/com/teamtriad/forpets/data/source/network/ResponseBody.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/AdoptFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/adapter/AdoptAdapter.kt
  app/src/main/java/com/teamtriad/forpets/ui/adopt/adapter/AdoptRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_adopt.xml
  app/src/main/res/layout/rv_item_adopt.xml
  app/src/main/res/values/strings.xml
Labels: improving, 리뷰요청

#31 이동봉사 화면을 구현했습니다.
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teamtriad/forpets/model/tmp/Markers.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportVolFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerVolListFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/LocationPickerDialogFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/bottomSheetDialog/LocationPickerForNavigation.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/marker/CustomClusterManager.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/marker/MarkerItem.kt
  app/src/main/res/color/selector_segmented_button_text_color.xml
  app/src/main/res/drawable/ic_destination.xml
  app/src/main/res/drawable/ic_paw.xml
  app/src/main/res/drawable/ic_travel.xml
  app/src/main/res/drawable/shape_circle_button.xml
  app/src/main/res/layout/fragment_transport.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
Labels: feat, 리뷰요청

#35 버튼들의 중복 클릭 시 발생하는 앱 종료 오류를 수정했습니다.
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportReqFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/TransportVolFragment.kt
  app/src/main/java/com/teamtriad/forpets/ui/transport/ViewPagerVolListFragment.kt
  app/src/main/res/layout/fragment_view_pager_vol_list.xml
Labels: fix, improving
